// Pulls live channel-level ad spend + conversion value (CV) from Triple
// Whale for Section 4 (Marketing & Sales Channel Performance), added
// 2026-08-31 per Tomer's request: "now that we have API connection to
// Triple whale, you update the sources directly from triple whale for
// Channels, Google Ads, TikTok Ads, Meta Ads, Microsoft Ads, impact.com,
// Criteo, Pinterest, Snapchat, ChatGPT Ads for the spend and the CV. CV from
// triple whale pixel. for snapchat and for impact.com pull the CV from the
// Channel CV on triple whale."
//
// AUTH: Triple Whale's public Data-Out API (https://api.triplewhale.com) is
// a completely separate credential from the MCP/connector access used to
// research and validate this feature — it needs its own portable API key,
// generated by Tomer himself from the Triple Whale app (Settings > API
// Keys > Generate an API Key; enable both the "Summary Page: Read" and
// "Pixel Attribution: Read" scopes to be safe, since the docs don't say
// which scope gates the SQL endpoint used below), then added to Render as
// the TRIPLEWHALE_API_KEY environment variable. Never paste that key into
// chat with Claude — it goes straight into Render's dashboard.
//
// If TRIPLEWHALE_API_KEY isn't set yet, fetchChannelPerformance() below
// resolves to null and the rest of the sync proceeds exactly as before
// (Section 4 just keeps showing the P&L-sheet snapshot) — so this deploy is
// safe to ship before Tomer has generated the key.
//
// DATA MODEL (validated 2026-08-31 by running real SQL against Triple
// Whale's warehouse for Aug 2026 on all 3 stores before writing this file):
//   - `pixel_joined_tvf(startDate, endDate, model)` is a ClickHouse
//     table-valued function joining ad-platform spend with both
//     channel-reported and Pixel-attributed conversion value, one row per
//     channel per day.
//   - `spend` = channel-reported ad spend (same figure for every model).
//   - `channel_reported_conversion_value` = the ad platform's OWN reported
//     revenue number — this is what Tomer calls "Channel CV".
//   - `order_revenue` (with model='Last Click') = Triple Whale's
//     Pixel-attributed revenue — this is what Tomer calls "CV from triple
//     whale pixel". model='Last Click' matches the existing convention
//     already established for the COM P&L monthly-update skill, where
//     "Last Click" is documented as "the MCP equivalent of what the browser
//     flow calls 'Pixel CV'".
//   - Confirmed live 2026-08-31: for Snapchat and Impact.com specifically,
//     order_revenue (Pixel CV) came back as 0 on ND.COM for Aug 2026 while
//     channel_reported_conversion_value was populated and non-zero — this
//     is exactly why Tomer's instruction carves out those two channels to
//     use Channel CV instead. (Same known pattern as Impact.com's existing
//     Pixel-CV-to-platform-CV fallback in the COM P&L monthly-update skill.)
//
// CONFIRMED CHANNEL COVERAGE (queried live 2026-08-31, Jan 1 - Aug 31 2026):
//   - ND.COM (natashadenona.myshopify.com): all 9 requested channels except
//     Microsoft Ads have live ad_table rows. Microsoft/Bing Ads has NO paid
//     channel rows on any of the 3 stores as of this writing — "bing" only
//     appears as a zero-spend organic-referral source, not a connected ad
//     platform. Section 4 will honestly show "No data" for Microsoft Ads
//     until/unless a Bing Ads integration is actually connected in Triple
//     Whale for a store.
//   - ND.EU (natasha-denona-trading.myshopify.com): only Google Ads, Meta
//     Ads, and Criteo are active; Impact.com revenue also flows in some
//     periods. TikTok Ads / Pinterest / Snapchat / ChatGPT Ads are not
//     currently run on this store.
//   - ND.IL (natashadenona-il.myshopify.com): only Google Ads and Meta Ads
//     are active via Triple Whale's ad connectors (matches the dashboard's
//     existing no_data flags for Microsoft Ads/Pinterest on this site).
//   None of this is hardcoded below — every channel is queried for every
//   site, and a channel with no rows for the period simply comes back
//   absent, which the frontend renders as "No data" (same as it already
//   does for IL's Microsoft Ads/Pinterest today).
//
// API DOCS: https://triplewhale.readme.io/reference/data-out-execute-custom-sql-query

const TRIPLEWHALE_SQL_URL = 'https://api.triplewhale.com/api/v2/orcabase/api/sql';

// Maps this app's internal site key to the Triple Whale shop identifier
// (same domains used throughout this project's Triple Whale research).
const TW_SHOP_ID = {
  com: 'natashadenona.myshopify.com',
  eu: 'natasha-denona-trading.myshopify.com',
  il: 'natashadenona-il.myshopify.com',
};

// Each entry: Triple Whale's own `channel` id (plus any known alternate
// spelling), the exact label string used in dashboard_v2.html's embedded
// Section 4 data (so the frontend merge can match existing rows by label),
// and which CV field Tomer wants for that channel.
const CHANNEL_MAP = [
  { ids: ['google-ads'], label: 'Google Ads', cv: 'pixel' },
  { ids: ['tiktok-ads'], label: 'TikTok Ads', cv: 'pixel' },
  { ids: ['facebook-ads'], label: 'Meta Ads', cv: 'pixel' },
  // Not confirmed active on any of the 3 stores as of 2026-08-31 (see file
  // header) — included so it starts working automatically the moment a
  // Bing/Microsoft Ads integration is connected in Triple Whale, without
  // needing another code change.
  { ids: ['microsoft-ads', 'bing-ads'], label: 'Microsoft Ads', cv: 'pixel' },
  { ids: ['criteo'], label: 'Criteo', cv: 'pixel' },
  { ids: ['pinterest-ads'], label: 'Pinterest', cv: 'pixel' },
  // New rows — not present in the dashboard's existing P&L-sourced Section 4
  // data for any site/month yet. The frontend merge adds these as brand new
  // channel rows the first time a Sync returns data for them.
  { ids: ['openai-ads'], label: 'ChatGPT Ads', cv: 'pixel' },
  { ids: ['impact'], label: 'impact.com', cv: 'channel' },
  { ids: ['snapchat-ads'], label: 'Snapchat', cv: 'channel' },
];

const ALL_CHANNEL_IDS = CHANNEL_MAP.flatMap((c) => c.ids);

// Fetches spend + CV per channel for one site over [start, end] (inclusive,
// YYYY-MM-DD, same range as the rest of a sync). Returns an array shaped
// like: [{ label, spend_actual, revenue_actual, cv_source }, ...] — one
// entry per channel that actually had rows for this period, or `null` if
// TRIPLEWHALE_API_KEY isn't configured yet or the request failed (logged,
// never thrown — a Triple Whale hiccup shouldn't break the rest of the
// Shopify sync).
async function fetchChannelPerformance(site, start, end) {
  const apiKey = process.env.TRIPLEWHALE_API_KEY;
  if (!apiKey) return null;

  const shopId = TW_SHOP_ID[site];
  if (!shopId) return null;

  // Single SQL pull covering every requested channel at once — spend and
  // both CV variants come back in the same row so we don't need to guess
  // ahead of time which CV column a given channel wants; that's applied
  // when mapping rows below.
  const query = `
    SELECT
      channel,
      SUM(spend) AS spend,
      SUM(channel_reported_conversion_value) AS channel_cv,
      SUM(order_revenue) AS pixel_cv
    FROM pixel_joined_tvf(startDate='${start}', endDate='${end}', model='Last Click')
    WHERE event_date >= '${start}' AND event_date <= '${end}'
      AND channel IN (${ALL_CHANNEL_IDS.map((id) => `'${id}'`).join(',')})
    GROUP BY channel
  `.trim();

  let json;
  try {
    const res = await fetch(TRIPLEWHALE_SQL_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
      },
      body: JSON.stringify({
        shopId,
        query,
        period: { startDate: start, endDate: end },
      }),
    });
    if (!res.ok) {
      const body = await res.text().catch(() => '');
      console.error(`Triple Whale SQL request failed for site=${site} (${res.status}): ${body.slice(0, 500)}`);
      return null;
    }
    json = await res.json();
  } catch (err) {
    console.error(`Triple Whale SQL request errored for site=${site}:`, err.message);
    return null;
  }

  // The API's exact response envelope isn't fully documented publicly as of
  // this writing — handle the two shapes that are plausible from the docs
  // ("results grouped by channel" as a bare array, or wrapped in a `rows`/
  // `data` field) rather than assuming one and breaking silently if Triple
  // Whale's actual shape differs slightly.
  const rows = Array.isArray(json) ? json : json.rows || json.data || [];
  if (!Array.isArray(rows) || !rows.length) return [];

  const byChannelId = new Map(rows.map((r) => [r.channel, r]));

  return CHANNEL_MAP.map((c) => {
    const row = c.ids.map((id) => byChannelId.get(id)).find(Boolean);
    if (!row) return { label: c.label, no_data: true };
    const spend = Number(row.spend || 0);
    const revenue = Number((c.cv === 'channel' ? row.channel_cv : row.pixel_cv) || 0);
    return {
      label: c.label,
      no_data: false,
      spend_actual: spend,
      revenue_actual: revenue,
      cv_source: c.cv, // 'pixel' or 'channel' — surfaced so the frontend note can say which
    };
  });
}

module.exports = { fetchChannelPerformance, CHANNEL_MAP, TW_SHOP_ID };
